apiVersion: v1
kind: Service
metadata:
  name: fhir-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
  selector:
    app: fhir-proxy
