apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapi-fhir
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hapi-fhir
  template:
    metadata:
      labels:
        app: hapi-fhir
    spec:
      containers:
        - name: hapi-fhir
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080


